/* 
 * File:   profiles_mpeg4_p2.cpp
 * Author: savop
 * 
 * Created on 7. Dezember 2009, 13:36
 */

#include "profiles/mpeg4_p2.h"

DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_SP_AAC = { "MPEG4_P2_MP4_SP_AAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_SP_HEAAC = { "MPEG4_P2_MP4_SP_HEAAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_SP_ATRAC3plus = { "MPEG4_P2_MP4_SP_ATRAC3plus", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_SP_AAC_LTP = { "MPEG4_P2_MP4_SP_AAC_LTP", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_SP_L2_AAC = { "MPEG4_P2_MP4_SP_L2_AAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_SP_L2_AMR = { "MPEG4_P2_MP4_SP_L2_AMR", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_SP_VGA_AAC = { "MPEG4_P2_MP4_SP_VGA_AAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_SP_VGA_HEAAC = { "MPEG4_P2_MP4_SP_VGA_HEAAC", "video/mp4"};

DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_AAC = { "MPEG4_P2_MP4_ASP_AAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_HEAAC = { "MPEG4_P2_MP4_ASP_HEAAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_HEAAC_MULT5 = { "MPEG4_P2_MP4_ASP_HEAAC_MULT5", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_ATRAC3plus = { "MPEG4_P2_MP4_ASP_ATRAC3plus", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_L5_SO_AAC = { "MPEG4_P2_MP4_ASP_L5_SO_AAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_L5_SO_HEAAC = { "MPEG4_P2_MP4_ASP_L5_SO_HEAAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_L5_SO_HEAAC_MULT5 = { "MPEG4_P2_MP4_ASP_L5_SO_HEAAC_MULT5", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_L5_SO_G726 = { "MPEG4_P2_MP4_ASP_L5_SO_G726", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_L4_SO_AAC = { "MPEG4_P2_MP4_ASP_L4_SO_AAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_L4_SO_HEAAC = { "MPEG4_P2_MP4_ASP_L4_SO_HEAAC", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_L4_SO_HEAAC_MULT5 = { "MPEG4_P2_MP4_ASP_L4_SO_HEAAC_MULT5", "video/mp4"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_MP4_ASP_L4_SO_G726 = { "MPEG4_P2_MP4_ASP_L4_SO_G726", "video/mp4"};

DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_AAC = { "MPEG4_P2_TS_SP_AAC", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_AAC_T = { "MPEG4_P2_TS_SP_AAC_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_AAC_ISO = { "MPEG4_P2_TS_SP_AAC_ISO", "video/mpeg"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG1_L3 = { "MPEG4_P2_TS_SP_MPEG1_L3", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG1_L3_T = { "MPEG4_P2_TS_SP_MPEG1_L3_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG1_L3_ISO = { "MPEG4_P2_TS_SP_MPEG1_L3_ISO", "video/mpeg"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_AC3 = { "MPEG4_P2_TS_SP_AC3", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_AC3_T = { "MPEG4_P2_TS_SP_AC3_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_AC3_ISO = { "MPEG4_P2_TS_SP_AC3_ISO", "video/mpeg"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG2_L2 = { "MPEG4_P2_TS_SP_MPEG2_L2", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG2_L2_T = { "MPEG4_P2_TS_SP_MPEG2_L2_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG2_L2_IS0 = { "MPEG4_P2_TS_SP_MPEG2_L2_IS0", "video/mpeg"};

DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_CO_AC3 = { "MPEG4_P2_TS_CO_AC3", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_CO_AC3_T = { "MPEG4_P2_TS_CO_AC3_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_CO_AC3_ISO = { "MPEG4_P2_TS_CO_AC3_ISO", "video/mpeg"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_CO_MPEG2_L2 = { "MPEG4_P2_TS_CO_MPEG2_L2", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_CO_MPEG2_L2_T = { "MPEG4_P2_TS_CO_MPEG2_L2_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_CO_MPEG2_L2_ISO = { "MPEG4_P2_TS_CO_MPEG2_L2_ISO", "video/mpeg"};

DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_AAC = { "MPEG4_P2_TS_ASP_AAC", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_AAC_T = { "MPEG4_P2_TS_ASP_AAC_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_AAC_ISO = { "MPEG4_P2_TS_ASP_AAC_ISO", "video/mpeg"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_MPEG1_L3 = { "MPEG4_P2_TS_ASP_MPEG1_L3", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_MPEG1_L3_T = { "MPEG4_P2_TS_ASP_MPEG1_L3_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_MPEG1_L3_ISO = { "MPEG4_P2_TS_ASP_MPEG1_L3_ISO", "video/mpeg"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_AC3 = { "MPEG4_P2_TS_ASP_AC3", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_AC3_T = { "MPEG4_P2_TS_ASP_AC3_T", "video/vnd.dlna.mpeg-tts"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_TS_ASP_AC3_ISO = { "MPEG4_P2_TS_ASP_AC3_ISO", "video/mpeg"};

DLNAProfile DLNA_PROFILE_MPEG4_P2_ASF_SP_G726 = { "MPEG4_P2_ASF_SP_G726", "video/x-ms-asf"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_ASF_ASP_L5_SO_G726 = { "MPEG4_P2_ASF_ASP_L5_SO_G726", "video/x-ms-asf"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_ASF_ASP_L4_SO_G726 = { "MPEG4_P2_ASF_ASP_L4_SO_G726", "video/x-ms-asf"};

DLNAProfile DLNA_PROFILE_MPEG4_H263_MP4_P0_L10_AAC = { "MPEG4_H263_MP4_P0_L10_AAC", "video/3gpp"};
DLNAProfile DLNA_PROFILE_MPEG4_H263_MP4_P0_L10_AAC_LTP = { "MPEG4_H263_MP4_P0_L10_AAC_LTP", "video/3gpp"};
DLNAProfile DLNA_PROFILE_MPEG4_H263_3GPP_P0_L10_AMR_WBplus = { "MPEG4_H263_3GPP_P0_L10_AMR_WBplus", "video/3gpp"};
DLNAProfile DLNA_PROFILE_MPEG4_H263_3GPP_P3_L10_AMR = { "MPEG4_H263_3GPP_P3_L10_AMR", "video/3gpp"};

DLNAProfile DLNA_PROFILE_MPEG4_P2_3GPP_SP_L0B_AAC = { "MPEG4_P2_3GPP_SP_L0B_AAC", "video/3gpp"};
DLNAProfile DLNA_PROFILE_MPEG4_P2_3GPP_SP_L0B_AMR = { "MPEG4_P2_3GPP_SP_L0B_AMR", "video/3gpp"};

DLNAVideoMapping MPEG4_P2_VIDEO_MAP[] = {
    { &DLNA_PROFILE_MPEG4_P2_3GPP_SP_L0B_AAC,           DLNA_VCP_3GPP,          DLNA_VPP_MPEG4_P2_SP_L0B,       DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_3GPP_SP_L0B_AMR,           DLNA_VCP_3GPP,          DLNA_VPP_MPEG4_P2_SP_L0B,       DLNA_APP_AMR },
    { &DLNA_PROFILE_MPEG4_P2_MP4_SP_L2_AAC,             DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_SP_L2,        DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_SP_L2_AMR,             DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_SP_L2,        DLNA_APP_AMR },
    { &DLNA_PROFILE_MPEG4_P2_MP4_SP_AAC,                DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_SP_HEAAC,              DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_HEAAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_SP_ATRAC3plus,         DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_ATRAC3plus },
    { &DLNA_PROFILE_MPEG4_P2_MP4_SP_AAC_LTP,            DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_AAC_LTP },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_AAC,                 DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_AAC_T,               DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_AAC_ISO,             DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG1_L3,            DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_MPEG1_L3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG1_L3_T,          DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_MPEG1_L3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG1_L3_ISO,        DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_MPEG1_L3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG2_L2,            DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_MPEG2_L2 },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG2_L2_T,          DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_MPEG2_L2 },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_MPEG2_L2_IS0,        DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_MPEG2_L2 },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_AC3,                 DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_AC3_T,               DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_SP_AC3_ISO,             DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_ASF_SP_G726,               DLNA_VCP_ASF,           DLNA_VPP_MPEG4_P2_SP_L3,        DLNA_APP_G726 },
    { &DLNA_PROFILE_MPEG4_P2_MP4_SP_VGA_AAC,            DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_SP_L3_VGA,    DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_SP_VGA_HEAAC,          DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_SP_L3_VGA,    DLNA_APP_HEAAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_AAC,               DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_HEAAC,             DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_HEAAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_HEAAC_MULT5,       DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_HEAAC_MULT5 },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_ATRAC3plus,        DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_ATRAC3plus },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_AAC,                DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_AAC_T,              DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_AAC_ISO,            DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_MPEG1_L3,           DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_MPEG1_L3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_MPEG1_L3_T,         DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_MPEG1_L3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_MPEG1_L3_ISO,       DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_MPEG1_L3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_AC3,                DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_AC3_T,              DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_ASP_AC3_ISO,            DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_ASP_L5,       DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_L5_SO_AAC,         DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L5_SO,    DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_L5_SO_HEAAC,       DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L5_SO,    DLNA_APP_HEAAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_L5_SO_HEAAC_MULT5, DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L5_SO,    DLNA_APP_HEAAC_MULT5 },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_L5_SO_G726,        DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L5_SO,    DLNA_APP_G726 },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_L4_SO_AAC,         DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L4_SO,    DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_L4_SO_HEAAC,       DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L4_SO,    DLNA_APP_HEAAC },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_L4_SO_HEAAC_MULT5, DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L4_SO,    DLNA_APP_HEAAC_MULT5 },
    { &DLNA_PROFILE_MPEG4_P2_MP4_ASP_L4_SO_G726,        DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_ASP_L4_SO,    DLNA_APP_G726 },
    { &DLNA_PROFILE_MPEG4_H263_MP4_P0_L10_AAC,          DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_H263_P0_L10,  DLNA_APP_AAC },
    { &DLNA_PROFILE_MPEG4_H263_MP4_P0_L10_AAC_LTP,      DLNA_VCP_MP4,           DLNA_VPP_MPEG4_P2_H263_P0_L10,  DLNA_APP_AAC_LTP },
    { &DLNA_PROFILE_MPEG4_H263_3GPP_P3_L10_AMR,         DLNA_VCP_3GPP,          DLNA_VPP_MPEG4_P2_H263_P3_L10,  DLNA_APP_AMR },
    { &DLNA_PROFILE_MPEG4_H263_3GPP_P0_L10_AMR_WBplus,  DLNA_VCP_3GPP,          DLNA_VPP_MPEG4_P2_H263_P0_L10,  DLNA_APP_AMR_WBplus },
    { &DLNA_PROFILE_MPEG4_P2_TS_CO_AC3,                 DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_CO,           DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_CO_AC3_T,               DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_CO,           DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_CO_AC3_ISO,             DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_CO,           DLNA_APP_AC3 },
    { &DLNA_PROFILE_MPEG4_P2_TS_CO_MPEG2_L2,            DLNA_VCP_MPEG2_TS,      DLNA_VPP_MPEG4_P2_CO,           DLNA_APP_MPEG2_L2 },
    { &DLNA_PROFILE_MPEG4_P2_TS_CO_MPEG2_L2_T,          DLNA_VCP_MPEG2_TS_T,    DLNA_VPP_MPEG4_P2_CO,           DLNA_APP_MPEG2_L2 },
    { &DLNA_PROFILE_MPEG4_P2_TS_CO_MPEG2_L2_ISO,        DLNA_VCP_MPEG2_TS_ISO,  DLNA_VPP_MPEG4_P2_CO,           DLNA_APP_MPEG2_L2 }
};